### ISSUE TITLE
How to add different authentication handlers?

### ISSUE THREAD

**Issue by piccinnigius** [qusly/qusly-core#37]
Hi, i can't figure how to add keyboard-interactive authentication handler (such as ssh2)
How can i do?

thanks so much

**Comment by xnerhu** [comment]
Hello!

I've merged your pull request and made a few adjustments. You can check out final API for [`Client.connect`](https://github.com/qusly/qusly-core/blob/master/docs/client.md#clientConnect) and [`IOptions`](https://github.com/qusly/qusly-core/blob/master/docs/types.md#iOptions).

```tsx
import { Client } from 'qusly-core';

const client = new Client();

client.connect(config, { sftp: { tryKeyboard: true } });
```

**Comment by xnerhu** [comment]
I'm closing this issue. If you have any questions, feel free to reopen.
