### ISSUE TITLE
readDir does not work for the specific folder (adding different path than ./ )  with FTP Protocol 

### ISSUE THREAD

**Issue by yus4u** [qusly/qusly-core#6]
I upgrade the library from 1.0.5 to 1.1.1, I discover the ls function not exist anymore and I have to use the readDir, it works perfectly with the SFTP but when I tried with the FTP, it doesn't work.

**Comment by xnerhu** [comment]
It's because when you list files with FTP, it doesn't change working directory. Compare these two versions. [1.1.0](https://github.com/qusly/qusly-core/blob/master/src/models/client.ts#L188) and [1.0.2](https://github.com/qusly/qusly-core/blob/c4fae75534e19fd029e8e996978459ebfcb5f3e8/src/models/client.ts#L325).

**Comment by yus4u** [comment]
I see, 
I thought it enough to add the path into the list function.

`  public readDir(path = './'): Promise<IReadDirRes> {
    return this._wrap(
      async () => {
        const files = await this._sftpClient.readDir(path);
        return files.map(file => formatFile(parseList(file.longname)[0]))
      },
      async () => {
        **const files = await this._ftpClient.list(path);**
        return files.map(file => formatFile(file));
      },
      'files'
    );
  }`


I was using the path in with the basic-ftp to have a list of files 

(https://www.npmjs.com/package/basic-ftp)
**list([path]): Promise<FileInfo[]>

List files and directories in the current working directory, or from the path if specified. Currently, this library only supports Unix- and DOS-style directory listings.**

**Comment by xnerhu** [comment]
[Fixed](https://github.com/qusly/qusly-core/commit/7996e113970e0db3e5d3abe2dda13527e94f1e51)
